### ISSUE TITLE
sort keys must be non-empty (can't see collections list in admin)

### ISSUE THREAD

**Issue by iamkevingreen** [orionjs/admin#7]
Getting a strange error on the index of a schema 'Uncaught Error: sort keys must be non-empty' from sort.js on line 22:

```
Minimongo.Sorter = function (spec, options) {
  var self = this;
  options = options || {};

  self._sortSpecParts = [];

  var addSpecPart = function (path, ascending) {
    if (!path)
      throw Error("sort keys must be non-empty");
    if (path.charAt(0) === '$')
      throw Error("unsupported sort key: " + path);
    self._sortSpecParts.push({
      path: path,
      lookup: makeLookupFunction(path, {forSort: true}),
      ascending: ascending
    });
  };
```

running the latest and greatest versions of all the orion stuff. I can create entries and they are added to the database but I can't see them in the admin list view.

**Comment by nicolaslopezj** [comment]
Can I see your entity definition code?

**Comment by iamkevingreen** [comment]
https://github.com/iamkevingreen/Orion-Portfolio-Thin/blob/master/schema/work.js the whole repo is public

**Comment by nicolaslopezj** [comment]
Please change the defaultIndexTableFields to tableColumns and the content inside. Read on http://orion.meteor.com
Sorry for not doing a changelog, I didn't knew people where really using this. 
Thanks!

**Comment by iamkevingreen** [comment]
Ahh... yeah I didn't update that area at all, I swore I browsed the documentation must have missed it. Thanks!
(also yeah, totally back this lil thing, wish you didn't use less but I got over it)

**Comment by nicolaslopezj** [comment]
If you don't like less you can use your own styles. Now ```orionjs:styles``` is not a dependency, and you style the admin however you want
